---
title: "Truth, beauty, and data + R and tidyverse"
linktitle: "1: Truth, beauty, and data + the tidyverse"
date: "2020-05-11"
read_date: "2020-05-11"
menu:
  content:
    parent: Course content
    weight: 1
type: docs
bibliography: "../../static/bib/references.bib"
csl: "../../static/bib/chicago-fullnote-bibliography-no-bib.csl"
slides: "01-slides"
output:
  blogdown::html_page:
    toc: true
---

## Readings

- The [syllabus](/syllabus/), [content](/content/), [lessons](/lesson/), [examples](/example/), and [assignments](/assigment/) pages for this class
- <i class="fas fa-book"></i> [Chapter 1](http://socviz.co/lookatdata.html) in Kieran Healy, *Data Visualization* [@Healy:2018]
- <i class="fas fa-book"></i> Chapters 2 and 3 in Alberto Cairo, *The Truthful Art* [@Cairo:2016] (*skim the introduction and chapter 1*)
- <i class="fas fa-external-link-square-alt"></i> [Study: Charts change hearts and minds better than words do](https://www.washingtonpost.com/news/wonk/wp/2018/06/15/study-charts-change-hearts-and-minds-better-than-words-do/?utm_term=.4474599c0d5e)


### Questions to reflect on

- How do we know what is true?
- Are facts truth?
- Why do we visualize data?
- What makes a great visualization?
- How do you choose which kind of visualization to use?


## Slides

The slides for today's lesson are available online as an HTML file. Use the buttons below to open the slides either as an interactive website or as a static PDF (for printing or storing for later). You can also click in the slides below and navigate through them with your left and right arrow keys.

`r blogdown::shortcode("slide-buttons")`

```{r show-slide-tabs, echo=FALSE, results="asis"}
source(here::here("R", "slide_tabs.R"))

sections <- tibble::tribble(
  ~name, ~slide, ~active,
  "Truth, beauty, and data", "1", TRUE,
  "Facts, truth, and beauty", "facts-truth-beauty", FALSE,
  "Data, truth, and beauty", "data-truth-beauty", FALSE,
  "Beautiful visualizations", "beautiful-visualizations", FALSE,
  "Class details", "class-details", FALSE,
)

slide_tabs(sections, "/slides/01-slides.html")
```

:::fyi
**Fun fact**: If you type <kbd>?</kbd> (or <kbd>shift</kbd> + <kbd>/</kbd>) while going through the slides, you can see a list of special slide-specific commands.
:::


## Videos

Videos for each section of the lecture are [available at this YouTube playlist](https://www.youtube.com/playlist?list=PLS6tnpTr39sHom5NPjrZAeMTYS5orTl9c).

- [Introduction](https://www.youtube.com/watch?v=tVcomh6jQ2Y&list=PLS6tnpTr39sHom5NPjrZAeMTYS5orTl9c)
- [Facts, truth, and beauty](https://www.youtube.com/watch?v=UbQ8IW3UI9E&list=PLS6tnpTr39sHom5NPjrZAeMTYS5orTl9c&)
- [Data, truth, and beauty](https://www.youtube.com/watch?v=DldFVc08YY4&list=PLS6tnpTr39sHom5NPjrZAeMTYS5orTl9c)
- [Beautiful visualizations](https://www.youtube.com/watch?v=6MTC9uGMNFg&list=PLS6tnpTr39sHom5NPjrZAeMTYS5orTl9c)
- [Class details](https://www.youtube.com/watch?v=_TclSs8iLMY&list=PLS6tnpTr39sHom5NPjrZAeMTYS5orTl9c)

You can also watch the playlist (and skip around to different sections) here:

<div class="embed-responsive embed-responsive-16by9">
<iframe class="embed-responsive-item" src="https://www.youtube.com/embed/videoseries?list=PLS6tnpTr39sHom5NPjrZAeMTYS5orTl9c" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>
