---
title: "Graphic design"
linktitle: "2: Graphic design"
date: "2020-05-12"
read_date: "2020-05-12"
menu:
  content:
    parent: Course content
    weight: 2
type: docs
bibliography: "../../static/bib/references.bib"
csl: "../../static/bib/chicago-fullnote-bibliography-no-bib.csl"
slides: "02-slides"
output:
  blogdown::html_page:
    toc: true
---

## Readings

- <i class="fas fa-book"></i> Chapter 5 in Alberto Cairo, *The Truthful Art* [@Cairo:2016]
- <i class="fas fa-book"></i> [Chapter 4](https://serialmentor.com/dataviz/color-basics.html) and [Chapter 22](https://serialmentor.com/dataviz/image-file-formats.html) in Claus Wilke, *Fundamentals of Data Visualization* [@Wilke:2018]
- <i class="far fa-file-pdf"></i> [Summary of CRAP graphic design principles](http://www.presentationzen.com/chapter6_spread.pdf) from Garr Reynolds, *Presentation Zen* [@Reynolds:2008]. These principles are from Robin Williams' [*The Non-Designer's Design & Type Books*](https://www.amazon.com/Non-Designers-Design-Book-4th/dp/0133966151) [@Williams:2008], which you should really get if you're interested in doing anything design-related ever. Her stuff is life-changing.
- <i class="fas fa-external-link-square-alt"></i> [Typography in ten minutes](https://practicaltypography.com/typography-in-ten-minutes.html). The rest of the *Practical Typography* book is phenomenal and you'd be remiss if you didn't read the whole thing and bookmark it for life, but for now just read this quick summary.
- <i class="fas fa-external-link-square-alt"></i> ["What's the Difference Between JPG, PNG, and GIF?"](https://gizmodo.com/5656669/whats-the-difference-between-jpg-png-and-gif)
- <i class="fas fa-external-link-square-alt"></i> ["File formats explained"](https://www.theglowstudio.com/file-formats-explained/)

### Questions to reflect on

- Why does graphic design matter when conveying truth?
- What makes something well designed (vs. poorly designed)?


## Slides

The slides for today's lesson are available online as an HTML file. Use the buttons below to open the slides either as an interactive website or as a static PDF (for printing or storing for later). You can also click in the slides below and navigate through them with your left and right arrow keys.

`r blogdown::shortcode("slide-buttons")`

```{r show-slide-tabs, echo=FALSE, results="asis"}
source(here::here("R", "slide_tabs.R"))

sections <- tibble::tribble(
  ~name, ~slide, ~active,
  "Graphic design", "1", TRUE,
  "Truth, beauty, stories, design", "truth-beauty-design", FALSE,
  "Graphic design and CRAP", "design-crap", FALSE,
  "Contrast", "contrast", FALSE,
  "Repetition", "repetition", FALSE,
  "Alignment", "alignment", FALSE,
  "Proximity", "proximity", FALSE,
  "Image types", "image-types", FALSE
)

slide_tabs(sections, "/slides/02-slides.html")
```

:::fyi
**Fun fact**: If you type <kbd>?</kbd> (or <kbd>shift</kbd> + <kbd>/</kbd>) while going through the slides, you can see a list of special slide-specific commands.
:::


## Videos

Videos for each section of the lecture are [available at this YouTube playlist](https://www.youtube.com/playlist?list=PLS6tnpTr39sEznTwka0EmWfkkphjncq7U).

- [Introduction](https://www.youtube.com/watch?v=ny7HYqyVNp4&list=PLS6tnpTr39sEznTwka0EmWfkkphjncq7U)
- [Truth, beauty, stories, design](https://www.youtube.com/watch?v=SXW0RtenLgk&list=PLS6tnpTr39sEznTwka0EmWfkkphjncq7U&)
- [Graphic design and CRAP](https://www.youtube.com/watch?v=iuEwh2EnIcw&list=PLS6tnpTr39sEznTwka0EmWfkkphjncq7U)
- [Image types](https://www.youtube.com/watch?v=j0aqBmRV66A&list=PLS6tnpTr39sEznTwka0EmWfkkphjncq7U)

You can also watch the playlist (and skip around to different sections) here:

<div class="embed-responsive embed-responsive-16by9">
<iframe class="embed-responsive-item" src="https://www.youtube.com/embed/videoseries?list=PLS6tnpTr39sEznTwka0EmWfkkphjncq7U" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>
