---
title: "Mapping data to graphics"
linktitle: "3: Mapping data to graphics"
date: "2020-05-13"
read_date: "2020-05-13"
menu:
  content:
    parent: Course content
    weight: 3
type: docs
bibliography: "../../static/bib/references.bib"
csl: "../../static/bib/chicago-fullnote-bibliography-no-bib.csl"
slides: "03-slides"
output:
  blogdown::html_page:
    toc: true
---

## Readings

- <i class="fab fa-youtube"></i> Hans Rosling, ["200 Countries, 200 Years, 4 Minutes"](https://www.youtube.com/watch?v=jbkSRLYSojo)
- <i class="fas fa-book"></i> [Chapter 2](https://serialmentor.com/dataviz/aesthetic-mapping.html) in Claus Wilke, *Fundamentals of Data Visualization* [@Wilke:2018]
- <i class="fas fa-book"></i> [Chapter 3](http://socviz.co/makeplot.html) in Kieran Healy, *Data Visualization* [@Healy:2018]

### Questions to reflect on

- Why is it important to visualize variables and data?
- What does it mean to map data to graph aesthetics?
- What data was mapped to which aesthetics in Rosling's video?


## Slides

The slides for today's lesson are available online as an HTML file. Use the buttons below to open the slides either as an interactive website or as a static PDF (for printing or storing for later). You can also click in the slides below and navigate through them with your left and right arrow keys.

`r blogdown::shortcode("slide-buttons")`

```{r show-slide-tabs, echo=FALSE, results="asis"}
source(here::here("R", "slide_tabs.R"))

sections <- tibble::tribble(
  ~name, ~slide, ~active,
  "Mapping data to graphics", "1", TRUE,
  "Data, aesthetics, & the grammar of graphics", "grammar-of-graphics", FALSE,
  "Grammatical layers", "grammatical-layers", FALSE,
  "Aesthetics in extra dimensions", "extra-dimensions", FALSE,
  "Tidy data", "tidy-data", FALSE
)

slide_tabs(sections, "/slides/03-slides.html")
```

:::fyi
**Fun fact**: If you type <kbd>?</kbd> (or <kbd>shift</kbd> + <kbd>/</kbd>) while going through the slides, you can see a list of special slide-specific commands.
:::


## Videos

Videos for each section of the lecture are [available at this YouTube playlist](https://www.youtube.com/playlist?list=PLS6tnpTr39sF-mpzuaQaDw5VoOgp359Z9).

- [Introduction](https://www.youtube.com/watch?v=ukDGvD3XXHg&list=PLS6tnpTr39sF-mpzuaQaDw5VoOgp359Z9)
- [Data, aesthetics, and the grammar of graphics](https://www.youtube.com/watch?v=S56YAocj-hk&list=PLS6tnpTr39sF-mpzuaQaDw5VoOgp359Z9&)
- [Grammatical layers](https://www.youtube.com/watch?v=DVr8ubJ7JHk&list=PLS6tnpTr39sF-mpzuaQaDw5VoOgp359Z9)
- [Aesthetics in extra dimensions](https://www.youtube.com/watch?v=pfYkWZcTHAM&list=PLS6tnpTr39sF-mpzuaQaDw5VoOgp359Z9)
- [Tidy data](https://www.youtube.com/watch?v=KHpZ1oa_99g&list=PLS6tnpTr39sF-mpzuaQaDw5VoOgp359Z9)

You can also watch the playlist (and skip around to different sections) here:

<div class="embed-responsive embed-responsive-16by9">
<iframe class="embed-responsive-item" src="https://www.youtube.com/embed/videoseries?list=PLS6tnpTr39sF-mpzuaQaDw5VoOgp359Z9" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>
