---
title: "Amounts and proportions"
linktitle: "4: Amounts and proportions"
date: "2020-05-14"
read_date: "2020-05-14"
menu:
  content:
    parent: Course content
    weight: 4
type: docs
bibliography: "../../static/bib/references.bib"
csl: "../../static/bib/chicago-fullnote-bibliography-no-bib.csl"
slides: "04-slides"
output:
  blogdown::html_page:
    toc: true
---

## Readings

- <i class="fas fa-book"></i> [Chapter 6](https://serialmentor.com/dataviz/visualizing-amounts.html) in Claus Wilke, *Fundamentals of Data Visualization* [@Wilke:2018]
- <i class="fas fa-book"></i> Chapter 6 in Alberto Cairo, *The Truthful Art* [@Cairo:2016]
- <i class="fas fa-book"></i> [Chapter 10](https://serialmentor.com/dataviz/visualizing-proportions.html) in Claus Wilke, *Fundamentals of Data Visualization* [@Wilke:2018]
- <i class="fas fa-external-link-square-alt"></i> [Engaging Readers with Square Pie/Waffle Charts](https://eagereyes.org/blog/2008/engaging-readers-with-square-pie-waffle-charts)
- <i class="fas fa-external-link-square-alt"></i> [Understanding Pie Charts](https://eagereyes.org/techniques/pie-charts)
- <i class="fas fa-external-link-square-alt"></i> [Square pie chart beats out the rest in perception study](https://flowingdata.com/2016/07/15/square-pie-chart-beats-out-the-rest-in-perception-study/)
- <i class="fab fa-twitter"></i> [Twitter thread](https://twitter.com/janinegibson/status/1244519429825802240) from John Burn-Murdoch on why the *Financial Times* uses log scales in their COVID-19 tracking charts
- <i class="fab fa-twitter"></i> [Tweet](https://twitter.com/jburnmurdoch/status/1238914490772701185) and [Twitter thread](https://twitter.com/jburnmurdoch/status/1242904596856614912) from John Burn-Murdoch on why the *Financial Times* doesn't use population-adjusted numbers in their COVID-19 tracking charts
- <i class="fab fa-twitter"></i> [Video from the *Financial Times* about the design decisions behind their COVID-19 tracking charts](https://twitter.com/janinegibson/status/1244519429825802240)

### Recommended

- <i class="fas fa-external-link-square-alt"></i> [See how to create your own COVID-19 tracking chart with R](https://robjhyndman.com/hyndsight/logratios-covid19/)

### Questions to reflect on

- How do these types of visualizations help or hinder our search for truth in data?
- What do you think of the *Financial Times* explanations of their use of absolute numbers (not per capita numbers) and log scales (not regular scales)? How have these decisions affected your perception of the pandemic? How have they affected others' perceptions?


## Slides

The slides for today's lesson are available online as an HTML file. Use the buttons below to open the slides either as an interactive website or as a static PDF (for printing or storing for later). You can also click in the slides below and navigate through them with your left and right arrow keys.

`r blogdown::shortcode("slide-buttons")`

```{r show-slide-tabs, echo=FALSE, results="asis"}
source(here::here("R", "slide_tabs.R"))

sections <- tibble::tribble(
  ~name, ~slide, ~active,
  "Amounts and proportions", "1", TRUE,
  "Reproducibility", "reproducibility", FALSE,
  "Amounts", "amounts", FALSE,
  "Proportions", "proportions", FALSE
)

slide_tabs(sections, "/slides/04-slides.html")
```

:::fyi
**Fun fact**: If you type <kbd>?</kbd> (or <kbd>shift</kbd> + <kbd>/</kbd>) while going through the slides, you can see a list of special slide-specific commands.
:::


## Videos

Videos for each section of the lecture are [available at this YouTube playlist](https://www.youtube.com/playlist?list=PLS6tnpTr39sEdnMYtNP3U3C2AsQZycEyP).

- [Introduction](https://www.youtube.com/watch?v=K8wELKhqgn0&list=PLS6tnpTr39sEdnMYtNP3U3C2AsQZycEyP)
- [Reproducibility](https://www.youtube.com/watch?v=pBpNaopKCVw&list=PLS6tnpTr39sEdnMYtNP3U3C2AsQZycEyP&)
- [Amounts](https://www.youtube.com/watch?v=5riA81CcHOY&list=PLS6tnpTr39sEdnMYtNP3U3C2AsQZycEyP)
- [Proportions](https://www.youtube.com/watch?v=3rDH0BWeDIQ&list=PLS6tnpTr39sEdnMYtNP3U3C2AsQZycEyP)

You can also watch the playlist (and skip around to different sections) here:

<div class="embed-responsive embed-responsive-16by9">
<iframe class="embed-responsive-item" src="https://www.youtube.com/embed/videoseries?list=PLS6tnpTr39sEdnMYtNP3U3C2AsQZycEyP" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>


```{example include=FALSE}
https://www.youtube.com/playlist?list=PLS6tnpTr39sEdnMYtNP3U3C2AsQZycEyP

https://youtu.be/K8wELKhqgn0
PMAP 8921 • (4) Amounts and Proportions: (0) Introduction

Introduction to the class session on amounts and proportions.

Access the slides, code, and other materials at the course website at https://datavizm20.classes.andrewheiss.com/content/03-content/


https://youtu.be/pBpNaopKCVw
PMAP 8921 • (4) Amounts and Proportions: (1) Reproducibility

Discussion about the importance of reproducible data analysis practices.

Access the slides, code, and other materials at the course website at https://datavizm20.classes.andrewheiss.com/content/03-content/


https://youtu.be/5riA81CcHOY
PMAP 8921 • (4) Amounts and Proportions: (2) Amounts

Discussion of best practices for visualizing amounts.

Access the slides, code, and other materials at the course website at https://datavizm20.classes.andrewheiss.com/content/03-content/


https://youtu.be/3rDH0BWeDIQ
PMAP 8921 • (4) Amounts and Proportions: (3) Proportions

Discussion of best practices for visualizing proportions.

Access the slides, code, and other materials at the course website at https://datavizm20.classes.andrewheiss.com/content/03-content/


https://youtu.be/zrT-ThV6U6M
PMAP 8921 • (4) Amounts and Proportions: Example

Complete walkthrough of how to visualize amounts and proportions with a bar chart, lollipop chart, strip plot, beeswarm plot, and heatmap using ggplot2 and R

Access the data, code, and other materials at https://datavizm20.classes.andrewheiss.com/example/04-example/
```
