---
title: "Uncertainty"
linktitle: "6: Uncertainty"
date: "2020-05-18"
read_date: "2020-05-18"
menu:
  content:
    parent: Course content
    weight: 6
type: docs
bibliography: "../../static/bib/references.bib"
csl: "../../static/bib/chicago-fullnote-bibliography-no-bib.csl"
slides: "06-slides"
output:
  blogdown::html_page:
    toc: true
---

## Readings

- <i class="fas fa-book"></i> [Chapter 7](https://serialmentor.com/dataviz/histograms-density-plots.html) in Claus Wilke, *Fundamentals of Data Visualization* [@Wilke:2018]
- <i class="fas fa-book"></i> Chapters 4, 7, and 11 in Alberto Cairo, *The Truthful Art* [@Cairo:2016]
- <i class="fas fa-external-link-square-alt"></i> [Why It's So Hard for Us to Visualize Uncertainty](https://hbr.org/2016/11/why-its-so-hard-for-us-to-visualize-uncertainty)
- <i class="fab fa-youtube"></i> [Amanda Cox's keynote address at the 2017 OpenVis Conf](https://www.youtube.com/watch?v=0L1tGo-DvD0)
- <i class="fas fa-external-link-square-alt"></i> [Communicating Uncertainty When Lives Are on the Line](https://eagereyes.org/blog/2017/communicating-uncertainty-when-lives-are-on-the-line)
- <i class="fas fa-external-link-square-alt"></i> [Showing uncertainty during the live election forecast](https://flowingdata.com/2016/11/15/showing-uncertainty-during-the-live-election-forecast/) & [Trolling the uncertainty dial](https://flowingdata.com/2017/06/27/trolling-the-uncertainty-dial/)

### Questions to reflect on

- Why is it important to deal with uncertainty in data?
- What was good or bad about the New York Times' 2016 live election guage?
- Why is it so hard to visualize uncertainty?
- Why is it so hard to communicate uncertainty to others?


## Slides

The slides for today's lesson are available online as an HTML file. Use the buttons below to open the slides either as an interactive website or as a static PDF (for printing or storing for later). You can also click in the slides below and navigate through them with your left and right arrow keys.

`r blogdown::shortcode("slide-buttons")`

```{r show-slide-tabs, echo=FALSE, results="asis"}
source(here::here("R", "slide_tabs.R"))

sections <- tibble::tribble(
  ~name, ~slide, ~active,
  "Uncertainty", "1", TRUE,
  "Communicating uncertainty", "communicating", FALSE,
  "Visualizing uncertainty", "visualizing", FALSE,
)

slide_tabs(sections, "/slides/06-slides.html")
```

:::fyi
**Fun fact**: If you type <kbd>?</kbd> (or <kbd>shift</kbd> + <kbd>/</kbd>) while going through the slides, you can see a list of special slide-specific commands.
:::


## Videos

Videos for each section of the lecture are [available at this YouTube playlist](https://www.youtube.com/playlist?list=PLS6tnpTr39sFmy596lUElQakCrKDSHUUU).

- [Introduction](https://www.youtube.com/watch?v=eZTp8Hninv4&list=PLS6tnpTr39sFmy596lUElQakCrKDSHUUU)
- [Communicating uncertainty](https://www.youtube.com/watch?v=TCQwkwlj4kM&list=PLS6tnpTr39sFmy596lUElQakCrKDSHUUU&)
- [Visualizing uncertainty](https://www.youtube.com/watch?v=X6zPEOPo-2M&list=PLS6tnpTr39sFmy596lUElQakCrKDSHUUU)

You can also watch the playlist (and skip around to different sections) here:

<div class="embed-responsive embed-responsive-16by9">
<iframe class="embed-responsive-item" src="https://www.youtube.com/embed/videoseries?list=PLS6tnpTr39sFmy596lUElQakCrKDSHUUU" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>


```{example include=FALSE}
https://www.youtube.com/playlist?list=PLS6tnpTr39sFmy596lUElQakCrKDSHUUU

https://youtu.be/eZTp8Hninv4
PMAP 8921 • (6) Uncertainty: (0) Introduction

Introduction to the class session on uncertainty.

Access the slides, code, and other materials at the course website at https://datavizm20.classes.andrewheiss.com/content/06-content/


https://youtu.be/TCQwkwlj4kM
PMAP 8921 • (6) Uncertainty: (1) Communicating uncertainty

Discussion about why uncertainty is both important and difficult to communicate 

Access the slides, code, and other materials at the course website at https://datavizm20.classes.andrewheiss.com/content/06-content/


https://youtu.be/X6zPEOPo-2M
PMAP 8921 • (6) Uncertainty: (2) Visualizing uncertainty

Overview of different methods for visualizing uncertainty, including histograms, density plots, ridge plots, box plots, violin plots, and half-versions of all these plots

Access the slides, code, and other materials at the course website at https://datavizm20.classes.andrewheiss.com/content/06-content/


https://youtu.be/40dW63jTbsk
PMAP 8921 • (6) Uncertainty: Example

Demonstration of how to create histograms, density plots, ridge plots, box plots, violin plots with ggplot2 and R

Download the data and see the polished code at https://datavizm20.classes.andrewheiss.com/example/06-example/
  
```
