---
title: "Comparisons"
linktitle: "8: Comparisons"
date: "2020-05-20"
read_date: "2020-05-20"
menu:
  content:
    parent: Course content
    weight: 8
type: docs
bibliography: "../../static/bib/references.bib"
csl: "../../static/bib/chicago-fullnote-bibliography-no-bib.csl"
slides: "08-slides"
output:
  blogdown::html_page:
    toc: true
---

## Readings

- <i class="fas fa-book"></i> [Chapter 9](https://serialmentor.com/dataviz/boxplots-violins.html) in Claus Wilke, *Fundamentals of Data Visualization* [@Wilke:2018]
- <i class="fas fa-external-link-square-alt"></i> Mike Bostock, ["Methods of Comparison, Compared"](https://observablehq.com/@mbostock/methods-of-comparison-compared). Explanation of the differences between showing relative differences, absolute differences, and log ratios.
- <i class="fas fa-external-link-square-alt"></i> [Sparkline theory and practice](https://www.edwardtufte.com/bboard/q-and-a-fetch-msg?msg_id=0001OR). This is a collection of posts by Edward Tufte about sparklines—scroll down a ways and check out his examples, analysis, and critiques.
- <i class="fas fa-external-link-square-alt"></i> [Time series sparklines](https://flowingdata.com/2017/01/24/one-dataset-visualized-25-ways/02-time-series-sparklines-2/)
- <i class="fas fa-external-link-square-alt"></i> [Comparisons with lollipop charts](https://uc-r.github.io/lollipop). If you're feeling adventurous (and you should!), do this tutorial as you read it.

### Reproducible examples

Reprexes (or reproducible examples) are the best way to (1) get help online and (2) fix issues on your own. 

Making a good reprex is tricky, but it's a very valuable skill to know (regardless of programming language!). Here are some helpful resources for making them:

- <i class="fas fa-external-link-square-alt"></i> [What's a reproducible example (`reprex`) and how do I do one?](https://community.rstudio.com/t/faq-whats-a-reproducible-example-reprex-and-how-do-i-do-one/5219)
- <i class="fas fa-external-link-square-alt"></i> [So you've been asked to make a reprex](https://www.jessemaegan.com/post/so-you-ve-been-asked-to-make-a-reprex/)
- <i class="fab fa-r-project"></i> [The reprex package](https://reprex.tidyverse.org/index.html)

### Questions to reflect on

- These readings all show a ton of new ways to present comparisons. Which ones are your favorite? Which ones didn't quite click with you? In what situations are some more appropriate than others?


## Slides

The slides for today's lesson are available online as an HTML file. Use the buttons below to open the slides either as an interactive website or as a static PDF (for printing or storing for later). You can also click in the slides below and navigate through them with your left and right arrow keys.

`r blogdown::shortcode("slide-buttons")`

```{r show-slide-tabs, echo=FALSE, results="asis"}
source(here::here("R", "slide_tabs.R"))

sections <- tibble::tribble(
  ~name, ~slide, ~active,
  "Comparisons", "1", TRUE,
  "Visualizing comparisons", "comparisons", FALSE,
  "Reproducible examples", "reprex", FALSE,
)

slide_tabs(sections, "/slides/08-slides.html")
```

:::fyi
**Fun fact**: If you type <kbd>?</kbd> (or <kbd>shift</kbd> + <kbd>/</kbd>) while going through the slides, you can see a list of special slide-specific commands.
:::


## Videos

Videos for each section of the lecture are [available at this YouTube playlist](https://www.youtube.com/playlist?list=PLS6tnpTr39sGAoxtYY1GgHm2ZRQmWeTiP).

- [Introduction](https://www.youtube.com/watch?v=pwvPAnjEHKk&list=PLS6tnpTr39sGAoxtYY1GgHm2ZRQmWeTiP)
- [Visualizing comparisons](https://www.youtube.com/watch?v=iJOPwPYxZZE&list=PLS6tnpTr39sGAoxtYY1GgHm2ZRQmWeTiP)
- [Reproducible examples](https://www.youtube.com/watch?v=Gv1U8IPxiOY&list=PLS6tnpTr39sGAoxtYY1GgHm2ZRQmWeTiP&)

You can also watch the playlist (and skip around to different sections) here:

<div class="embed-responsive embed-responsive-16by9">
<iframe class="embed-responsive-item" src="https://www.youtube.com/embed/videoseries?list=PLS6tnpTr39sGAoxtYY1GgHm2ZRQmWeTiP" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>


```{example include=FALSE}
https://www.youtube.com/playlist?list=PLS6tnpTr39sGAoxtYY1GgHm2ZRQmWeTiP

https://youtu.be/pwvPAnjEHKk
PMAP 8921 • (8) Comparisons: (0) Introduction

Introduction to the class session on comparisons

Access the slides, code, and other materials at the course website at https://datavizm20.classes.andrewheiss.com/content/08-content/


https://youtu.be/iJOPwPYxZZE
PMAP 8921 • (8) Comparisons: (1) The dangers of dual y-axes

Overview of different methods for visualizing comparisons, including bar and lollipop charts, small multiples, sparklines, and bump plots

Access the slides, code, and other materials at the course website at https://datavizm20.classes.andrewheiss.com/content/08-content/


https://youtu.be/Gv1U8IPxiOY
PMAP 8921 • (8) Comparisons: (2) Reproducible examples

Discussion of best practices for creating reproducible examples with R when debugging

Access the slides, code, and other materials at the course website at https://datavizm20.classes.andrewheiss.com/content/08-content/
  
See also "What's a reproducible example and how do I do one?" (https://community.rstudio.com/t/faq-whats-a-reproducible-example-reprex-and-how-do-i-do-one/5219) and "So you've been asked to make a reprex" (https://www.jessemaegan.com/post/so-you-ve-been-asked-to-make-a-reprex/)


https://youtu.be/tCnfTLHtMs8
PMAP 8921 • (8) Comparisons: Example

Demonstration of how to create small multiples, sparklines, and slopegraphs with ggplot2 and R

Download the data and see the polished code at https://datavizm20.classes.andrewheiss.com/example/08-example/
  
```
