---
title: "Interactivity"
linktitle: "10: Interactivity"
date: "2020-05-22"
read_date: "2020-05-22"
menu:
  content:
    parent: Course content
    weight: 10
type: docs
bibliography: "../../static/bib/references.bib"
csl: "../../static/bib/chicago-fullnote-bibliography-no-bib.csl"
slides: "10-slides"
output:
  blogdown::html_page:
    toc: true
---

## Readings

### Explorable explanations

- <i class="fas fa-trophy"></i> Marcel Salathé and Nicky Case, ["What Happens Next: COVID-19 Futures, Explained with Playable Situations"](https://ncase.me/covid-19/)
- <i class="fas fa-external-link-square-alt"></i> Brett Victor, ["Explorable Explanations"](http://worrydream.com/ExplorableExplanations/)
- <i class="fas fa-trophy"></i> Look at [some of the explorable explorations here](https://explorabl.es/)
- <i class="fas fa-external-link-square-alt"></i> Dragicevic, Jansen, Sarma, Kay, and Chevalier, ["Explorable Multiverse Analyses"](https://explorablemultiverse.github.io/). Use Chrome, open Example 1, scroll to page 2, and click on some of the blue text to change the results of the paper *within the paper itself*. This is magical. R Markdown can't quite get *this* interactive in real-time, but you can knit different versions of a document with slightly different parameters and options.

### Dashboards

- <i class="fas fa-external-link-square-alt"></i> Look at [some of these examples of Shiny apps](https://shiny.rstudio.com/gallery/)
- <i class="fas fa-external-link-square-alt"></i> Stephanie Evergreen, ["How a Dashboard Changes the Conversation"](https://stephanieevergreen.com/dashboard-conversation/)
- <i class="fas fa-external-link-square-alt"></i> Stephanie Evergreen, ["The Problem with Dashboards (and a Solution)"](https://stephanieevergreen.com/problem-with-dashboards/)
- <i class="fas fa-external-link-square-alt"></i> Stephen Few, ["2012 Perceptual Edge Dashboard Design Competition: A Solution of My Own"](https://www.stephen-few.com/blog/2013/01/08/2012-perceptual-edge-dashboard-design-competition-a-solution-of-my-own/)
- <i class="fas fa-file-pdf"></i> Skim through Stephen Few's [presentation on Information Dashboard Design](http://blogs.ischool.berkeley.edu/i247s12/files/2012/01/Dashboard-Design-Overview-Presentation.pdf)
- <i class="fab fa-google"></i> Google "dashboard design" and skim through some of the thousands of articles about what makes a good (and bad) dashboard

### Questions to reflect on

- How helpful (or unhelpful) are explorable explanations?
- Have you seen examples of good dashboards before this class? Bad dashboards? What makes them good or bad?


## Slides

The slides for today's lesson are available online as an HTML file. Use the buttons below to open the slides either as an interactive website or as a static PDF (for printing or storing for later). You can also click in the slides below and navigate through them with your left and right arrow keys.

`r blogdown::shortcode("slide-buttons")`

```{r show-slide-tabs, echo=FALSE, results="asis"}
source(here::here("R", "slide_tabs.R"))

sections <- tibble::tribble(
  ~name, ~slide, ~active,
  "Interactivity", "1", TRUE,
  "Making interactive graphs", "interactive-graphs", FALSE,
  "Sharing content", "sharing-content", FALSE
)

slide_tabs(sections, "/slides/10-slides.html")
```

:::fyi
**Fun fact**: If you type <kbd>?</kbd> (or <kbd>shift</kbd> + <kbd>/</kbd>) while going through the slides, you can see a list of special slide-specific commands.
:::


## Videos

Videos for each section of the lecture are [available at this YouTube playlist](https://www.youtube.com/playlist?list=PLS6tnpTr39sHxE_PbXWE2RC0mpN6syYhe).

- [Introduction](https://www.youtube.com/watch?v=L6BGy0-0X-w&list=PLS6tnpTr39sHxE_PbXWE2RC0mpN6syYhe)
- [Making interactive graphics](https://www.youtube.com/watch?v=gyVFhQNCp80&list=PLS6tnpTr39sHxE_PbXWE2RC0mpN6syYhe)
- [Sharing content](https://www.youtube.com/watch?v=lubDKJhlx9g&list=PLS6tnpTr39sHxE_PbXWE2RC0mpN6syYhe&)

You can also watch the playlist (and skip around to different sections) here:

<div class="embed-responsive embed-responsive-16by9">
<iframe class="embed-responsive-item" src="https://www.youtube.com/embed/videoseries?list=PLS6tnpTr39sHxE_PbXWE2RC0mpN6syYhe" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>


```{cat include=FALSE}
https://www.youtube.com/playlist?list=PLS6tnpTr39sHxE_PbXWE2RC0mpN6syYhe

https://youtu.be/L6BGy0-0X-w
PMAP 8921 • (10) Interactivity: (0) Introduction

Introduction to the class session on interactivity

Access the slides, code, and other materials at the course website at https://datavizm20.classes.andrewheiss.com/content/10-content/


https://youtu.be/gyVFhQNCp80
PMAP 8921 • (10) Interactivity: (1) Making interactive graphics

Discussion of how to make interactive graphs in R with plotly (with ggplotly()), with flexdashboard, and with Shiny

Access the slides, code, and other materials at the course website at https://datavizm20.classes.andrewheiss.com/content/10-content/


https://youtu.be/lubDKJhlx9g
PMAP 8921 • (10) Interactivity: (2) Sharing content

Discussion of how to share knitted R Markdown documents through RPubs and other online services

Access the slides, code, and other materials at the course website at https://datavizm20.classes.andrewheiss.com/content/10-content/
```
