---
title: Readings, lectures, and videos
menu:
  content:
    parent: Overview
    weight: 1
type: docs
weight: 1
---

Each class session has a set of required readings that you should complete ***before*** watching the lecture or working through the lesson. 

I've included a set of questions that might guide your reflection response. You should not try to respond to all of these (or any of them if you don't want to)—they'll just help you know what to look for and think about as you read.

Every class session also has a YouTube playlist of short recorded videos for each of the lecture sections. The lecture slides are special HTML files made with the R package [**xaringan**](https://bookdown.org/yihui/rmarkdown/xaringan.html) (R can do so much!). On each class session page you'll buttons for opening the presentation in a new tab or for downloading a PDF of the slides in case you want to print them or store them on your computer:

<p style="text-align:center;"><span class="btn btn-primary btn-lg"><i class="fas fa-external-link-alt"></i> View all slides in new window</span> <span class="btn btn-primary btn-lg"><i class="far fa-file-pdf"></i> Download PDF of all slides</span></p>

The slides are also embedded on each page. You can click in the slides and navigate through them with <kbd>←</kbd> and <kbd>→</kbd>. If you type <kbd>?</kbd> (or <kbd>shift</kbd> + <kbd>/</kbd>) while viewing the slides you can see a list of slide-specific commands (like <kbd>f</kbd> for fullscreen or <kbd>p</kbd> for presenter mode if you want to see my notes).

