---
title: Assignment overview
menu:
  assignment:
    parent: Overview
    weight: 1
type: docs
weight: 1
output:
  blogdown::html_page:
    toc: true
---

You will get the most of out this class if you:

1. Engage with the readings and lecture materials
2. Regularly use R

Each type of assignment in this class helps with one of these strategies.


## Reflections

To encourage engagement with the course content, you'll need to write a ≈150 word reflection about the readings and lectures for the day. That's fairly short: there are ≈250 words on a typical double-spaced page in Microsoft Word (500 when single-spaced). 

You can do a lot of different things with this memo: discuss something you learned from the course content, write about the best or worst data visualization you saw recently, connect the course content to your own work, etc. These reflections let you explore and answer some of the key questions of this course, including:

- What is truth? How is truth related to visualization?
- Why do we visualize data?
- What makes a great visualization? What makes a bad visualization?
- How do you choose which kind of visualization to use?
- What is the role of stories in presenting analysis?

The course content for each day will also include a set of questions specific to that topic. *You do not have to answer all (or any) of these questions*. That would be impossible. They exist to guide your thinking, that's all.

I will grade these memos using a check system:

- ✔+: (*11.5 points (115%) in gradebook*) Reflection shows phenomenal thought and engagement with the course content. I will not assign these often.
- ✔: (*10 points (100%) in gradebook*) Reflection is thoughtful, well-written, and shows engagement with the course content. This is the expected level of performance.
- ✔−: (*5 points (50%) in gradebook*) Reflection is hastily composed, too short, and/or only cursorily engages with the course content. This grade signals that you need to improve next time. I will hopefully not assign these often.

Notice that is essentially a pass/fail or completion-based system. I'm not grading your writing ability, I'm not counting the exact number of words you're writing, and I'm not looking for encyclopedic citations of every single reading to prove that you did indeed read everything. I'm looking for thoughtful engagement, that's all. Do good work and you'll get a ✓.

You will turn these reflections in via iCollege. You will write them using R Markdown and they will be the first section of your daily exercises (see below). 


## Exercises

Each class session has [interactive lessons](/lesson/) and [fully annotated examples](/example/) of code that teach and demonstrate how to do specific tasks in R. However, without practicing these principles and making graphics on your own, you won't remember what you learn! 

To practice working with **ggplot2** and making data-based graphics, you will complete a brief set of exercises for each class session. These exercises will have 1–3 short tasks that are directly related to the topic for the day. You need to show that you made a good faith effort to work each question. The problem sets will also be graded using a check system:

- ✔+: (*11.5 points (115%) in gradebook*) Exercises are 100% completed. Every task was attempted and answered, and most answers are correct. Knitted document is clean and easy to follow. Work is exceptional. I will not assign these often.
- ✔: (*10 points (100%) in gradebook*) Exercises are 70–99% complete and most answers are correct. This is the expected level of performance.
- ✔−: (*5 points (50%) in gradebook*) Exercises are less than 70% complete and/or most answers are incorrect. This indicates that you need to improve next time. I will hopefully not assign these often.

Note that this is also essentially a pass/fail system. I'm not grading your coding ability, I'm not checking each line of code to make sure it produces some exact final figure, and I'm not looking for perfect. Also note that a ✓ does not require 100% completion—you will sometimes get stuck with weird errors that you can't solve, or the demands of pandemic living might occasionally become overwhelming. I'm looking for good faith effort, that's all. Try hard, do good work, and you'll get a ✓.

You may (and should!) work together on the exercises, but you must turn in your own answers.

You will turn these exercises in using iCollege. You will include your reflection in the first part of the document—the rest will be your exercise tasks.


## Mini projects

To give you practice with the data and design principles you'll learn in this class, you will complete two mini projects. I will provide you with real-world data and pose one or more questions—you will make a pretty picture to answer those questions.

The mini projects will be graded using a check system:

- ✔+: (*85 points (≈115%) in gradebook*) Project is phenomenally well-designed and uses advanced R techniques. The project uncovers an important story that is not readily apparent from just looking at the raw data. I will not assign these often.
- ✔: (*75 points (100%) in gradebook*) Project is fine, follows most design principles, answers a question from the data, and uses R correctly. This is the expected level of performance.
- ✔−: (*37.5 points (50%) in gradebook*) Project is missing large components, is poorly designed, does not answer a relevant question, and/or uses R incorrectly. This indicates that you need to improve next time. I will hopefully not assign these often.

Because these mini projects give you practice for the final project, I will provide you with substantial feedback on your design and code.


## Final project

At the end of the course, you will demonstrate your data visualization skills by completing a final project.

[Complete details for the final project (including past examples of excellent projects) are here.](/assignment/final-project/)

**There is no final exam. This project is your final exam.**

The project will ***not*** be graded using a check system. Instead I will use a rubric to grade four elements of your project:

1. Technical skills
2. Visual design
3. Truth and beauty
4. Story

If you've engaged with the course content and completed the exercises and mini projects throughout the course, you should do just fine with the final project.
